name: Codeball AI Code Review

on:
  pull_request:
    branches: [ "master" ]

jobs:
  review:

    runs-on: ubuntu-latest

    steps:
    - name: Codeball AI Code Review
      uses: sturdy-dev/codeball-action@v2.6.0

